/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

/**
 *
 * @author Usuario
 */
public class Temperatura extends javax.swing.JFrame {

    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelConversorTemp = new javax.swing.JLabel();
        jLabelSeleccioneEntrada = new javax.swing.JLabel();
        textoTempareatura = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnInCelsius = new javax.swing.JRadioButton();
        btnInFarenheit = new javax.swing.JRadioButton();
        btnInKelvin = new javax.swing.JRadioButton();
        btnOutCelsius = new javax.swing.JRadioButton();
        btnOutFarenheit = new javax.swing.JRadioButton();
        btnOutKelvin = new javax.swing.JRadioButton();
        jLabelIngreseTemperatura = new javax.swing.JLabel();
        jLabelSeleccioneSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelConversorTemp.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabelConversorTemp.setText("Conversor de Temperatura");
        jLabelConversorTemp.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabelConversorTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConversorTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSeleccioneEntrada.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSeleccioneEntrada.setText("Seleccione escala de entrada");

        textoTempareatura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textoTempareatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoTempareatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTempareaturaActionPerformed(evt);
            }
        });

        btnConvertir.setBackground(new java.awt.Color(204, 204, 204));
        btnConvertir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/Image20250828205419.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(btnInCelsius);
        btnInCelsius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInCelsius.setText("Celsius");
        btnInCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInCelsiusActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnInFarenheit);
        btnInFarenheit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInFarenheit.setText("Farenheit");
        btnInFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInFarenheitActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnInKelvin);
        btnInKelvin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInKelvin.setText("Kelvin");
        btnInKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInKelvinActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnOutCelsius);
        btnOutCelsius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutCelsius.setText("Celsius");
        btnOutCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutCelsiusActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnOutFarenheit);
        btnOutFarenheit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutFarenheit.setText("Farenheit");

        buttonGroup2.add(btnOutKelvin);
        btnOutKelvin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutKelvin.setText("Kelvin");

        jLabelIngreseTemperatura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelIngreseTemperatura.setText("Ingrese temperatura");

        jLabelSeleccioneSalida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSeleccioneSalida.setText("Seleccione escala de salida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSeleccioneSalida, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSeleccioneEntrada, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInCelsius)
                            .addComponent(btnOutCelsius))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInFarenheit)
                            .addComponent(textoTempareatura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOutFarenheit))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOutKelvin)
                            .addComponent(btnInKelvin)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabelIngreseTemperatura)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelSeleccioneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInCelsius)
                    .addComponent(btnInFarenheit)
                    .addComponent(btnInKelvin))
                .addGap(28, 28, 28)
                .addComponent(jLabelIngreseTemperatura)
                .addGap(18, 18, 18)
                .addComponent(textoTempareatura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabelSeleccioneSalida)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutFarenheit)
                    .addComponent(btnOutKelvin)
                    .addComponent(btnOutCelsius))
                .addGap(36, 36, 36)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoTempareaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTempareaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTempareaturaActionPerformed

    private void btnInCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInCelsiusActionPerformed
        btnOutCelsius.setEnabled(false);
        btnOutFarenheit.setEnabled(true);
        btnOutKelvin.setEnabled(true);
    }//GEN-LAST:event_btnInCelsiusActionPerformed

    private void btnInKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInKelvinActionPerformed
        btnOutKelvin.setEnabled(false);
        btnOutFarenheit.setEnabled(true);
        btnOutCelsius.setEnabled(true);
    }//GEN-LAST:event_btnInKelvinActionPerformed

    private void btnOutCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutCelsiusActionPerformed

    private void btnInFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInFarenheitActionPerformed
        btnOutFarenheit.setEnabled(false);
        btnOutKelvin.setEnabled(true);
        btnOutCelsius.setEnabled(true);
    }//GEN-LAST:event_btnInFarenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JRadioButton btnInCelsius;
    private javax.swing.JRadioButton btnInFarenheit;
    private javax.swing.JRadioButton btnInKelvin;
    private javax.swing.JRadioButton btnOutCelsius;
    private javax.swing.JRadioButton btnOutFarenheit;
    private javax.swing.JRadioButton btnOutKelvin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabelConversorTemp;
    private javax.swing.JLabel jLabelIngreseTemperatura;
    private javax.swing.JLabel jLabelSeleccioneEntrada;
    private javax.swing.JLabel jLabelSeleccioneSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textoTempareatura;
    // End of variables declaration//GEN-END:variables
}
