/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Temperatura extends javax.swing.JFrame {

    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelSeleccioneEntrada = new javax.swing.JLabel();
        textoTempareatura = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnInCelsius = new javax.swing.JRadioButton();
        btnInFarenheit = new javax.swing.JRadioButton();
        btnInKelvin = new javax.swing.JRadioButton();
        btnOutCelsius = new javax.swing.JRadioButton();
        btnOutFarenheit = new javax.swing.JRadioButton();
        btnOutKelvin = new javax.swing.JRadioButton();
        jLabelIngreseTemperatura = new javax.swing.JLabel();
        jLabelSeleccioneSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabelSeleccioneEntrada.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSeleccioneEntrada.setText("Seleccione escala de entrada:");

        textoTempareatura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textoTempareatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoTempareatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTempareaturaActionPerformed(evt);
            }
        });

        btnConvertir.setBackground(new java.awt.Color(204, 204, 204));
        btnConvertir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/Image20250828205419.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnInCelsius);
        btnInCelsius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInCelsius.setText("Celsius");
        btnInCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInCelsiusActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnInFarenheit);
        btnInFarenheit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInFarenheit.setText("Fahrenheit");
        btnInFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInFarenheitActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnInKelvin);
        btnInKelvin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInKelvin.setText("Kelvin");
        btnInKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInKelvinActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnOutCelsius);
        btnOutCelsius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutCelsius.setText("Celsius");
        btnOutCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutCelsiusActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnOutFarenheit);
        btnOutFarenheit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutFarenheit.setText("Fahrenheit");

        buttonGroup2.add(btnOutKelvin);
        btnOutKelvin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOutKelvin.setText("Kelvin");

        jLabelIngreseTemperatura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelIngreseTemperatura.setText("Ingrese temperatura");

        jLabelSeleccioneSalida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSeleccioneSalida.setText("Seleccione escala de salida:");

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor de Temperatura");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(textoTempareatura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelIngreseTemperatura))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnInCelsius)
                                .addGap(80, 80, 80)
                                .addComponent(btnInFarenheit)
                                .addGap(80, 80, 80)
                                .addComponent(btnInKelvin))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeleccioneEntrada)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnOutCelsius)
                                .addGap(80, 80, 80)
                                .addComponent(btnOutFarenheit)
                                .addGap(80, 80, 80)
                                .addComponent(btnOutKelvin))
                            .addComponent(jLabelSeleccioneSalida))))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabelSeleccioneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInCelsius)
                    .addComponent(btnInFarenheit)
                    .addComponent(btnInKelvin))
                .addGap(34, 34, 34)
                .addComponent(jLabelIngreseTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoTempareatura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabelSeleccioneSalida)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutFarenheit)
                    .addComponent(btnOutKelvin)
                    .addComponent(btnOutCelsius))
                .addGap(36, 36, 36)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoTempareaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTempareaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTempareaturaActionPerformed

    private void btnInCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInCelsiusActionPerformed
        btnOutCelsius.setEnabled(false);
        btnOutFarenheit.setEnabled(true);
        btnOutKelvin.setEnabled(true);
    }//GEN-LAST:event_btnInCelsiusActionPerformed

    private void btnInKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInKelvinActionPerformed
        btnOutKelvin.setEnabled(false);
        btnOutFarenheit.setEnabled(true);
        btnOutCelsius.setEnabled(true);
    }//GEN-LAST:event_btnInKelvinActionPerformed

    private void btnOutCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutCelsiusActionPerformed

    private void btnInFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInFarenheitActionPerformed
        btnOutFarenheit.setEnabled(false);
        btnOutKelvin.setEnabled(true);
        btnOutCelsius.setEnabled(true);
    }//GEN-LAST:event_btnInFarenheitActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        try {
              String jtext = textoTempareatura.getText();
double grados = Double.parseDouble(jtext);
        if (btnInCelsius.isSelected()&& btnOutFarenheit.isSelected()) {
            
            JOptionPane.showMessageDialog(this, grados * 9.0 / 5 + 32 + " ° Fahrenheit");
        } else if(btnInCelsius.isSelected()&& btnOutKelvin.isSelected()){
            JOptionPane.showMessageDialog(this, grados + 273.15 + " ° Kelvin");
        } else if(btnInFarenheit.isSelected()&& btnOutCelsius.isSelected()){
            JOptionPane.showMessageDialog(this,(grados - 32) * 5.0 / 9 +  " ° Celsius");
        } else if(btnInFarenheit.isSelected()&& btnOutKelvin.isSelected()){
            JOptionPane.showMessageDialog(this,(grados - 32) * 5.0 / 9 + 273.15 + " ° Kelvin");
        }else if(btnInKelvin.isSelected()&& btnOutCelsius.isSelected()){
            JOptionPane.showMessageDialog(this,grados - 273.15 + " ° Celsius");
        } else if(btnInKelvin.isSelected()&& btnOutFarenheit.isSelected()){
            JOptionPane.showMessageDialog(this,(grados - 273.15) * 9.0 / 5 + 32 + " ° Fahrenheit");
        }else{
             JOptionPane.showMessageDialog(this,  "Error, ingrese una de las opciones. ");
        }  
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,  "Error de entrada. Debe ingresar un numero. ");
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JRadioButton btnInCelsius;
    private javax.swing.JRadioButton btnInFarenheit;
    private javax.swing.JRadioButton btnInKelvin;
    private javax.swing.JRadioButton btnOutCelsius;
    private javax.swing.JRadioButton btnOutFarenheit;
    private javax.swing.JRadioButton btnOutKelvin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIngreseTemperatura;
    private javax.swing.JLabel jLabelSeleccioneEntrada;
    private javax.swing.JLabel jLabelSeleccioneSalida;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textoTempareatura;
    // End of variables declaration//GEN-END:variables
}
